name: Deploy development

on:
  push:
    branches:
      - main

jobs:
  deployment:
    concurrency: "development deployment"
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: development
    secrets: inherit
